from __future__ import annotations

import logging
import time
from collections import deque
from dataclasses import dataclass

from ..whatsapp import jid as J
from .backends import (BackendError, Context, extract_media, fetch_media,
                       render, reply_via_model, reply_via_webhook)
from .settings import TriggerSettings

log = logging.getLogger(__name__)


@dataclass
class Decision:
    fired: bool
    reason: str
    reply: str | None = None
    backend: str | None = None
    media: int = 0
    error: bool = False
    notified: str | None = None

    def public(self) -> dict:
        return {"fired": self.fired, "reason": self.reason,
                "backend": self.backend, "media": self.media,
                "notified": self.notified,
                "reply_preview": (self.reply or "")[:120] or None}


@dataclass
class Inbound:
    chat_jid: str
    message_id: str
    sender_jid: str
    text: str
    is_from_me: bool
    is_group: bool
    mentioned_me: bool = False


def now_in(tz_name: str):
    from datetime import datetime

    try:
        from zoneinfo import ZoneInfo

        return datetime.now(ZoneInfo(tz_name))
    except Exception:
        return datetime.now()


class TriggerEngine:
    def __init__(self, runtime, http=None):
        self.rt = runtime
        self._http = http
        self.settings = TriggerSettings()
        self._cooldown: dict[str, float] = {}
        self._recent_hour: deque[float] = deque()
        self._generated: set[str] = set()
        self.log: deque[dict] = deque(maxlen=100)


    async def load(self) -> TriggerSettings:
        from .settings import SETTINGS_KEY
        self.settings = TriggerSettings.from_dict(await self.rt.store.get_kv(SETTINGS_KEY))
        return self.settings

    async def save(self, settings: TriggerSettings) -> None:
        from .settings import SETTINGS_KEY
        self.settings = settings
        await self.rt.store.put_kv(SETTINGS_KEY, settings.to_dict())

    def note_generated(self, message_id: str) -> None:
        self._generated.add(message_id)
        if len(self._generated) > 2000:
            self._generated = set(list(self._generated)[-1000:])


    def _why_not(self, msg: Inbound) -> str | None:
        s = self.settings

        if msg.is_from_me:
            return "message is our own"
        if msg.message_id in self._generated:
            return "message was generated by this bot (loop guard)"
        if not (msg.text or "").strip():
            return "message has no text"
        if J.is_ignorable(msg.chat_jid):
            return "status/newsletter pseudo-chat"

        ok, why = s.ready()
        if not ok:
            return why

        if self.rt.wa is None or not self.rt.wa.sync.state.ready:
            return "still syncing — replies are held until history finishes"

        if not s.hours.open_at(now_in(s.hours.timezone)):
            return f"outside active hours ({s.hours.start}–{s.hours.end})"

        blocked = s.guardrails.blocked_reason(msg.text)
        if blocked:
            return f"guardrail: {blocked}"

        chat = J.normalise(msg.chat_jid)
        if msg.is_group:
            if s.reply.groups == "none":
                return "group replies are off"
            if s.reply.groups == "allowlist" and chat not in _norm(s.reply.groups_allowlist):
                return "group is not in the allowlist"
            if s.reply.require_mention_in_groups and not msg.mentioned_me:
                return "group replies require being mentioned"
        else:
            if s.reply.personal == "none":
                return "personal replies are off"
            if s.reply.personal == "allowlist" and chat not in _norm(s.reply.personal_allowlist):
                return "sender is not in the allowlist"

        now = time.monotonic()
        last = self._cooldown.get(chat)
        if last is not None and now - last < s.reply.cooldown_seconds:
            return f"cooldown: {int(s.reply.cooldown_seconds - (now - last))}s left for this chat"

        while self._recent_hour and now - self._recent_hour[0] > 3600:
            self._recent_hour.popleft()
        if len(self._recent_hour) >= s.reply.max_replies_per_hour:
            return f"hourly cap reached ({s.reply.max_replies_per_hour})"

        return None


    async def consider(self, msg: Inbound) -> Decision:
        watched = await self._watch(msg)

        why = self._why_not(msg)
        if why:
            if why.startswith("outside active hours"):
                await self._after_hours(msg)
            if why.startswith("guardrail:"):
                d = await self._refuse(msg, why)
                return d if not watched else self._touch(d, watched)
            return self._record(Decision(False, why, notified=watched))

        try:
            ctx = await self._context(msg)
        except Exception as exc:
            return self._record(Decision(False, f"could not build context: {exc}",
                                         error=True))

        backend = self.settings.backend
        try:
            if backend == "model":
                text = await reply_via_model(self.settings.model, ctx, self._http,
                                             self.settings.notify.handoff_marker)
            else:
                token = ""
                if not self.settings.webhook.expect_reply:
                    from ..delivery import mint

                    token = await mint(self.rt.store, msg.chat_jid,
                                       self.settings.webhook.token_ttl_seconds)
                text = await reply_via_webhook(
                    self.settings.webhook, ctx, self._http, token,
                    self.settings.notify.handoff_marker)
        except BackendError as exc:
            reason = f"{backend} backend failed: {exc}"
            g = self.settings.guardrails
            if g.send_fallback_on_error and g.fallback_message:
                await self._say(msg, g.fallback_message)
            if self.settings.notify.on_error:
                await self._notify(msg, reason)
            return self._record(Decision(False, reason, backend=backend, error=True))

        text = (text or "").strip()

        if backend == "webhook" and not self.settings.webhook.expect_reply:
            return self._record(Decision(False, "handed to the webhook",
                                         backend=backend))

        marker = self.settings.notify.handoff_marker
        handoff = bool(marker and marker in text)
        if handoff:
            text = text.replace(marker, "").strip()
            fallback = (self.settings.guardrails.fallback_message or "").strip()
            if fallback:
                text = fallback

        media: list[str] = []
        if self.settings.send_media:
            text, media = extract_media(text)

        if not text and not media:
            if handoff:
                g = self.settings.guardrails
                if g.fallback_message:
                    await self._say(msg, g.fallback_message)
                notified = await self._notify(msg, "the assistant did not understand")
                return self._record(Decision(bool(g.fallback_message),
                                             "not understood — handed over",
                                             g.fallback_message, backend,
                                             notified=notified))
            return self._record(Decision(False, "backend returned an empty reply",
                                         backend=backend))
        limit = self.settings.reply.max_reply_chars
        if len(text) > limit:
            text = text[:limit].rsplit(" ", 1)[0] + "…"

        chat = J.normalise(msg.chat_jid)
        self._cooldown[chat] = time.monotonic()
        self._recent_hour.append(time.monotonic())

        await self._disclose(msg, ctx)

        sent_media = 0
        try:
            if self.settings.show_typing:
                await self.rt.wa.set_typing(chat, True)
            if text:
                sent = await self.rt.wa.send_text(chat, text)
                if sent.get("message_id"):
                    self.note_generated(sent["message_id"])
            sent_media = await self._send_media(chat, media)
        except Exception as exc:
            return self._record(Decision(False, f"send failed: {exc}", text, backend,
                                         error=True))
        finally:
            if self.settings.show_typing:
                try:
                    await self.rt.wa.set_typing(chat, False)
                except Exception:
                    pass

        notified = None
        if handoff and self.settings.notify.on_handoff:
            notified = await self._notify(msg, "the assistant asked for a human")

        return self._record(Decision(True, "sent", text, backend,
                                     media=sent_media,
                                     notified=notified or watched))

    async def _watch(self, msg: Inbound) -> str | None:
        n = self.settings.notify
        if not n.watching or msg.is_from_me or msg.message_id in self._generated:
            return None
        if self.rt.wa is None or not self.rt.wa.sync.state.ready:
            return None
        reason = n.watch_reason(msg.text, msg.sender_jid, msg.chat_jid, msg.is_group)
        if not reason:
            return None
        return await self._notify(msg, reason)

    def _touch(self, d: Decision, notified: str) -> Decision:
        d.notified = d.notified or notified
        return d


    async def _send_media(self, chat: str, urls: list[str]) -> int:
        import base64

        n = 0
        for url in urls[:4]:
            try:
                data, _ctype, kind = await fetch_media(
                    url, self.settings.max_media_bytes, self._http)
                sent = await self.rt.wa.send_media(
                    chat, base64.b64encode(data).decode(), kind)
                if sent.get("message_id"):
                    self.note_generated(sent["message_id"])
                n += 1
            except Exception as exc:
                log.warning("media %s not sent: %s", url, exc)
        return n

    async def _say(self, msg: Inbound, text: str) -> None:
        try:
            sent = await self.rt.wa.send_text(J.normalise(msg.chat_jid), text)
            if sent.get("message_id"):
                self.note_generated(sent["message_id"])
        except Exception as exc:
            log.warning("fallback message not sent: %s", exc)

    async def _refuse(self, msg: Inbound, reason: str) -> Decision:
        g = self.settings.guardrails
        chat = J.normalise(msg.chat_jid)
        now = time.monotonic()
        last = self._cooldown.get(chat)
        if last is None or now - last >= g_cooldown(self.settings):
            if g.send_fallback_when_blocked and g.fallback_message:
                self._cooldown[chat] = now
                await self._say(msg, g.fallback_message)
        notified = None
        if self.settings.notify.on_blocked:
            notified = await self._notify(msg, reason)
        return self._record(Decision(False, reason, notified=notified))

    async def _after_hours(self, msg: Inbound) -> bool:
        text = (self.settings.hours.after_hours_message or "").strip()
        if not text:
            return False
        chat = J.normalise(msg.chat_jid)
        day = now_in(self.settings.hours.timezone).strftime("%Y-%m-%d")
        key = f"afterhours.{chat}.{day}"
        if await self.rt.store.get_kv(key):
            return False
        try:
            sent = await self.rt.wa.send_text(chat, text)
            if sent.get("message_id"):
                self.note_generated(sent["message_id"])
            await self.rt.store.put_kv(key, {"at": time.time()})
            return True
        except Exception as exc:
            log.warning("after-hours note to %s failed: %s", chat, exc)
            return False

    async def _disclose(self, msg: Inbound, ctx) -> bool:
        d = self.settings.disclosure
        if not d.enabled or not (d.message or "").strip():
            return False
        chat = J.normalise(msg.chat_jid)
        key = f"disclosed.{chat}"
        if await self.rt.store.get_kv(key):
            return False
        try:
            sent = await self.rt.wa.send_text(chat, render(d.message, ctx))
            if sent.get("message_id"):
                self.note_generated(sent["message_id"])
            await self.rt.store.put_kv(key, {"at": time.time()})
            return True
        except Exception as exc:
            log.warning("disclosure to %s failed: %s", chat, exc)
            return False

    async def _notify(self, msg: Inbound, reason: str) -> str | None:
        n = self.settings.notify
        if n.route == "me":
            target = J.normalise(getattr(self.rt.wa, "self_jid", "") or "")
        elif n.route == "chat":
            target = J.normalise(msg.chat_jid)
        elif n.route == "number":
            target = J.to_jid(n.jid)
        else:
            target = ""
        if not target:
            log.debug("no alert: route=%r resolved to nothing", n.route)
            return None
        try:
            ctx = await self._context(msg)
            ctx.reason = reason
            body = render(n.template, ctx).strip()
            sent = await self.rt.wa.send_text(target, body)
            if sent.get("message_id"):
                self.note_generated(sent["message_id"])
            return target
        except Exception as exc:
            log.warning("notification to %s failed: %s", target, exc)
            return None

    async def _context(self, msg: Inbound) -> Context:
        s = self.settings
        n = (s.model.history_messages if s.backend == "model"
             else s.webhook.history_messages)
        rows = await self.rt.store.get_messages(msg.chat_jid, limit=max(1, n) + 1)
        chat = await self.rt.store.get_chat(msg.chat_jid)
        book = self.rt.contacts

        history = []
        for m in reversed(rows):
            if m.message_id == msg.message_id or not m.text:
                continue
            speaker = ("You" if m.is_from_me
                       else book.display_name(m.sender_jid or "", push_name=m.sender_name))
            history.append((m.is_from_me, speaker, m.text))

        me = getattr(self.rt.wa, "push_name", "") or "me"
        ctx = Context(
            policy=s.guardrails.as_prompt(),
            message=msg.text,
            chat_name=book.display_name(msg.chat_jid, chat_name=chat.name if chat else None),
            chat_jid=msg.chat_jid,
            sender_name=book.display_name(msg.sender_jid or msg.chat_jid),
            sender_jid=msg.sender_jid,
            me_name=me,
            message_id=msg.message_id,
            timestamp=str(int(time.time())),
            history=history[-n:],
        )
        ctx.system = render(s.model.system_prompt, ctx)
        return ctx

    def _record(self, d: Decision) -> Decision:
        entry = {"at": time.time(), **d.public()}
        self.log.appendleft(entry)
        if d.error:
            log.warning("auto-reply FAILED: %s", d.reason)
        elif d.fired:
            log.info("auto-reply sent via %s", d.backend)
        else:
            log.debug("auto-reply skipped: %s", d.reason)
        return d


def g_cooldown(settings) -> int:
    return max(0, settings.reply.cooldown_seconds)


def _norm(values: list[str]) -> set[str]:
    return {J.normalise(v) for v in values or []}
